name: flutter_artist_router
description: A declarative Navigator 2.0 router client supporting dynamic intermediate route pruning, automated memory disposes, and standalone history stack mutations.
version: 0.9.3
resolution: workspace
homepage: https://o7planning.github.io

environment:
  sdk: ^3.11.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_artist_core: ^0.9.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter: 
